### ISSUE TITLE
侧边栏使用时 无法调出设置配置

### ISSUE THREAD

**Issue by hey-sm** [jinhuan138/vscode-book-reader#3]
![PixPin_2024-12-09_11-14-57](https://github.com/user-attachments/assets/70c7bdd9-8be3-4bdd-b852-044a272279fa)
作者你好   是我使用的问题吗

**Comment by jinhuan138** [comment]
![image](https://github.com/user-attachments/assets/2f5a901b-f566-4da5-ad06-c1def098cbbf)
我这试了是可以的，能看看开发人员工具有报错吗

**Comment by hey-sm** [comment]
![PixPin_2024-12-09_13-59-25](https://github.com/user-attachments/assets/6f252c32-7184-47cb-980c-61aa887c7e17)
s      是侧边栏使用的时候没有设置选项   无法鼠标滚动内容

**Comment by jinhuan138** [comment]
默认鼠标滚动翻页触发频率没那么高，获取焦点时也可以使用↑↓←→翻页，侧边栏部分设置和主页面是共用的，侧边栏滚动模式v1.0.12已修复

**Comment by hey-sm** [comment]
需要打开该设置即可生效     感谢作者
![image](https://github.com/user-attachments/assets/05a17ac1-d42b-4e99-a6b1-85081c9e2bfa)
